export const SET_LOCATION_DATA = 'SET_LOCATION_DATA';
export const SET_ISLOADING_LOCATION = 'SET_ISLOADING_LOCATION';

export const SET_CURRENT_FORECAST_WEATHERAPI = 'SET_CURRENT_FORECAST_WEATHERAPI';
export const SET_DAILY_FORECAST_WEATHERAPI = 'SET_DAILY_FORECAST_WEATHERAPI';
export const SET_HOURLY_FORECAST_WEATHERAPI = 'SET_HOURLY_FORECAST_WEATHERAPI';

export const SET_CURRENT_FORECAST_OPENWEATHER = 'SET_CURRENT_FORECAST_OPENWEATHER';
export const SET_DAILY_FORECAST_OPENWEATHER = 'SET_DAILY_FORECAST_OPENWEATHER';
export const SET_HOURLY_FORECAST_OPENWEATHER = 'SET_HOURLY_FORECAST_OPENWEATHER';

export const SET_WEATHER_MODE = 'SET_WEATHER_MODE';
export const SET_WEATHER_SOURCE = 'SET_WEATHER_SOURCE';